branch-defaults:
  circle_ci:
    environment: proversity-nodebb
    group_suffix: null
  master:
    environment: proversity-nodebb
    group_suffix: null
container_commands:
  01_create_config.yml:
    command: |
      echo "{" > config.json
      echo "    \"url\": \"${APP_NODEBB_URL}"," >> config.json
      echo "    \"secret\": \"${APP_NODEBB_SECRET}\"," >> config.json
      echo "    \"port\": 8001," >> config.json
      echo "    \"database\": \"mongo\"," >> config.json
      echo "    \"mongo\": {" >> config.json
      echo "        \"host\": \"${APP_MONGO_HOST}\"," >> config.json
      echo "        \"port\": \"${APP_MONGO_PORT}\"," >> config.json
      echo "        \"username\": \"${APP_MONGO_USERNAME}\"," >> config.json
      echo "        \"password\": \"${APP_MONGO_PASSWORD}\"," >> config.json
      echo "        \"database\": \"${APP_MONGO_DATABASE}\"," >> config.json
      echo "        \"options\": {" >> config.json
      echo "            \"mongos\": {" >> config.json
      echo "                \"ssl\": true," >> config.json
      echo "                \"sslValidate\": false" >> config.json
      echo "            }" >> config.json
      echo "        }" >> config.json
      echo "    }" >> config.json
      echo "}" >> config.json
      chown nodejs: config.json
    cwd: /var/app/current
global:
  application_name: proversity-nodebb
  default_ec2_keyname: proversity-eu-west-1
  default_platform: Node.js
  default_region: eu-west-1
  profile: eb-proversity
  sc: git
