branch-defaults:
  circle_ci:
    environment: proversity-nodebb
    group_suffix: null
  master:
    environment: proversity-nodebb
    group_suffix: null
container_commands:
  01_create_config.yml:
    command: "printenv > printenv.txt"
global:
  application_name: proversity-nodebb
  default_ec2_keyname: proversity-eu-west-1
  default_platform: Node.js
  default_region: eu-west-1
  profile: eb-proversity
  sc: git
