apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodebb.fullname" . }}
data: 
  config.user.json: |
    {{ .Values.nodebb.configYaml | toJson }}
  config.managed.json: |
    {
      "upload_path": "/usr/src/app/public/uploads",
      "isCluster": true,
      "url": {{ printf (ternary "https://%s" "http://%s" .Values.nodebb.tls) .Values.nodebb.domain | quote }},
      "database": {{ .Values.nodebb.database | quote }}
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodebb.fullname" . }}-config-init-script
data: 
  entrypoint.sh: |-
    #!/bin/bash
    jq -s 'def deepmerge(a;b):
      reduce b[] as $item (a;
      reduce ($item | keys_unsorted[]) as $key (.;
      $item[$key] as $val | ($val | type) as $type | .[$key] = if ($type == "object") then
              deepmerge({}; [if .[$key] == null then {} else .[$key] end, $val])
      elif ($type == "array") then
              (.[$key] + $val | unique)
      else
              $val
      end)
      );
      deepmerge({}; .)' /secrets/database.json /config.managed.json /configmaps/config.user.json | tee /opt/config/config.json