apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodebb.fullname" . }}
type: Opaque
stringData: 
  database.json: |
    {
      "redis": {
{{- if and .Values.global.database.managed .Values.global.redis.managed }}
        "host": "{{ template "common.names.fullname" .Subcharts.redis }}-master",
{{- else }}
        "host": {{ .Values.redis.auth.host | quote }},
{{- end }}
        "port": {{ .Values.redis.auth.port | quote }},
        "password": {{ .Values.redis.auth.password | quote }},
        "database": {{ .Values.redis.auth.database | quote }}
      },
      "mongo": {
{{- if and .Values.global.database.managed .Values.global.mongodb.managed }}
        "host": "{{ template "mongodb.service.nameOverride" .Subcharts.mongodb }}",
{{- else }}
        "host": {{ .Values.mongodb.auth.host | quote }},
{{- end }}
        "port": {{ .Values.mongodb.auth.port | quote }},
        "username": {{ .Values.mongodb.auth.username | quote }},
        "password": {{ .Values.mongodb.auth.password | quote }},
        "database": {{ .Values.mongodb.auth.database | quote }}
      },
      "postgres": {
{{- if and .Values.global.database.managed .Values.global.postgresql.managed }}
        "host": "{{ template "postgresql.v1.primary.fullname" .Subcharts.postgresql }}",
{{- else }}
        "host": {{ .Values.postgresql.auth.host | quote }},
{{- end }}
        "port": {{ .Values.postgresql.auth.port | quote }},
        "username": {{ .Values.postgresql.auth.username | quote }},
        "password": {{ .Values.postgresql.auth.password | quote }},
        "database": {{ .Values.postgresql.auth.database | quote }}
      }
    }
    