name: Lint

on:
  push:
    branches:
      - master
      - develop
      - bootstrap5
  pull_request:
    branches:
      - master
      - develop
      - bootstrap5

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  lint:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    name: Lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    env:
      TEST_ENV: ${{ matrix.test_env || 'production' }}

    steps:
      - uses: actions/checkout@v2

      - run: cp install/package.json package.json

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: NPM Install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Run ESLint
        run: npm run lint
