name: K8S Integration test 

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    name: K8S Integration test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-kubectl@v3
      - uses: AbsaOSS/k3d-action@v2
        name: "Create Single Cluster"
        with:
            cluster-name: "nodebb-test"
            args: --agents 1